# Generated by Django 5.1.15 on 2026-07-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profiladministrateur_profilenseignant_profiletudiant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('seuil_faible', models.FloatField(default=30.0, help_text='Score <= seuil_faible => risque Faible', verbose_name='Seuil Faible')),
                ('seuil_modere', models.FloatField(default=60.0, help_text='Score <= seuil_modere => risque Modere ; > => Eleve', verbose_name='Seuil Modere')),
                ('ponderation_notes', models.FloatField(default=0.4, verbose_name='Ponderation N (notes)')),
                ('ponderation_credits', models.FloatField(default=0.3, verbose_name='Ponderation C (credits)')),
                ('ponderation_ue_echec', models.FloatField(default=0.2, verbose_name='Ponderation U (UE echec)')),
                ('ponderation_absenteisme', models.FloatField(default=0.1, verbose_name='Ponderation A (absenteisme)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Parametre d'alerte",
                'verbose_name_plural': "Parametres d'alerte",
                'db_table': 'parametre_alerte',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('type', models.CharField(choices=[('echec_ue', 'Échec UE'), ('absence', 'Absence'), ('credits', 'Crédits insuffisants'), ('risque', 'Risque global')], default='risque', max_length=50, verbose_name='Type')),
                ('niveau_risque', models.CharField(choices=[('Faible', 'Faible (≤ 30)'), ('Modere', 'Modéré (31–60)'), ('Eleve', 'Élevé (> 60)')], default='Modere', max_length=10, verbose_name='Niveau de risque')),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Traitee', 'Traitée'), ('Archivee', 'Archivée')], default='Active', max_length=15, verbose_name='Statut')),
                ('score_risque', models.FloatField(blank=True, null=True, verbose_name="Score au moment de l'alerte")),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='accounts.profiletudiant', verbose_name='Etudiant')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traitee par')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=10, verbose_name='Priorite')),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='alerts.alerte', verbose_name='Alerte')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'db_table': 'recommandation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['etudiant', 'statut'], name='idx_alerte_etu_statut'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['niveau_risque'], name='idx_alerte_niveau'),
        ),
    ]
