# Generated by Django 5.1.15 on 2026-07-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtlCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('ressource', models.CharField(max_length=30, unique=True, verbose_name='Ressource')),
                ('derniere_synchro', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
                ('nb_total_synchro', models.PositiveIntegerField(default=0, verbose_name='Nb total synchronisé')),
            ],
            options={
                'verbose_name': 'Point de synchronisation ETL',
                'verbose_name_plural': 'Points de synchronisation ETL',
                'db_table': 'etl_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec'), ('partiel', 'Partiel')], default='en_cours', max_length=15, verbose_name='Statut')),
                ('source_mode', models.CharField(default='mock', max_length=10, verbose_name='Mode source')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('dernier_since', models.CharField(blank=True, default='', max_length=30, verbose_name="Dernier 'since' traité")),
                ('nb_etudiants_extraits', models.PositiveIntegerField(default=0, verbose_name='Étudiants extraits')),
                ('nb_ue_extraits', models.PositiveIntegerField(default=0, verbose_name='UE extraits')),
                ('nb_resultats_extraits', models.PositiveIntegerField(default=0, verbose_name='Résultats extraits')),
                ('nb_presences_extraites', models.PositiveIntegerField(default=0, verbose_name='Présences extraites')),
                ('nb_etudiants_charges', models.PositiveIntegerField(default=0, verbose_name='Étudiants chargés')),
                ('nb_ue_charges', models.PositiveIntegerField(default=0, verbose_name='UE chargés')),
                ('nb_resultats_charges', models.PositiveIntegerField(default=0, verbose_name='Résultats chargés')),
                ('nb_erreurs', models.PositiveIntegerField(default=0, verbose_name='Erreurs')),
                ('log', models.TextField(blank=True, default='', verbose_name='Journal détaillé')),
            ],
            options={
                'verbose_name': 'Exécution ETL',
                'verbose_name_plural': 'Exécutions ETL',
                'db_table': 'etl_run',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EtlExecutionErreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('etape', models.CharField(default='', max_length=30, verbose_name='Étape')),
                ('ressource', models.CharField(blank=True, default='', max_length=50, verbose_name='Ressource')),
                ('message', models.TextField(verbose_name="Message d'erreur")),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erreurs_log', to='etl.etlrun', verbose_name='Exécution')),
            ],
            options={
                'verbose_name': 'Erreur ETL',
                'verbose_name_plural': 'Erreurs ETL',
                'db_table': 'etl_erreur',
                'ordering': ['-created_at'],
            },
        ),
    ]
