# Generated by Django 5.1.15 on 2026-07-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('service', models.CharField(blank=True, default='', max_length=100, verbose_name='Service')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_profil_administrateur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
                'db_table': 'profil_administrateur',
            },
        ),
        migrations.CreateModel(
            name='ProfilEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('departement', models.CharField(blank=True, default='', max_length=100, verbose_name='Département')),
                ('specialite', models.CharField(blank=True, default='', max_length=100, verbose_name='Spécialité')),
                ('grade', models.CharField(blank=True, default='', max_length=50, verbose_name='Grade')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_profil_enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil enseignant',
                'verbose_name_plural': 'Profils enseignants',
                'db_table': 'profil_enseignant',
                'ordering': ['utilisateur__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('matricule', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matricule')),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='L1', max_length=5, verbose_name='Niveau LMD')),
                ('filiere', models.CharField(blank=True, default='', max_length=100, verbose_name='Filière')),
                ('promotion', models.CharField(blank=True, default='', max_length=20, verbose_name='Promotion')),
                ('annee_scolaire', models.CharField(blank=True, default='', max_length=9, verbose_name='Année scolaire')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_profil_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil étudiant',
                'verbose_name_plural': 'Profils étudiants',
                'db_table': 'profil_etudiant',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='ResponsablePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('filiere_geree', models.CharField(blank=True, default='', max_length=100, verbose_name='Filière gérée')),
                ('niveau_gere', models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='', max_length=5, verbose_name='Niveau géré')),
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilite', to='accounts.profilenseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Responsable pédagogique',
                'verbose_name_plural': 'Responsables pédagogiques',
                'db_table': 'responsable_pedagogique',
            },
        ),
    ]
