# Generated by Django 5.1.15 on 2026-07-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profiladministrateur_profilenseignant_profiletudiant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code UE')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitule')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Credits ECTS')),
                ('semestre_numero', models.PositiveSmallIntegerField(default=1, verbose_name='Numero de semestre')),
                ('ue_type', models.CharField(choices=[('obligatoire', 'Obligatoire'), ('optionnel', 'Optionnel')], default='obligatoire', max_length=15, verbose_name='Type')),
            ],
            options={
                'verbose_name': "Unite d'Enseignement",
                'verbose_name_plural': "Unites d'Enseignement",
                'db_table': 'unite_enseignement',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ParcoursAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('annee_scolaire', models.CharField(default='', max_length=9, verbose_name='Annee scolaire')),
                ('filiere', models.CharField(blank=True, default='', max_length=100, verbose_name='Filiere')),
                ('niveau', models.CharField(blank=True, default='', max_length=5, verbose_name='Niveau')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('diplome', 'Diplome'), ('abandon', 'Abandon')], default='en_cours', max_length=15, verbose_name='Statut')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='accounts.profiletudiant', verbose_name='Etudiant')),
            ],
            options={
                'verbose_name': 'Parcours academique',
                'verbose_name_plural': 'Parcours academiques',
                'db_table': 'parcours_academique',
                'ordering': ['etudiant__matricule', '-annee_scolaire'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numero')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Annee')),
                ('annee_scolaire', models.CharField(default='', max_length=9, verbose_name='Annee scolaire')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestre',
                'ordering': ['annee', 'numero'],
                'unique_together': {('numero', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne generale /20')),
                ('credits_total', models.PositiveIntegerField(default=0, verbose_name='Credits total vises')),
                ('credits_acquis', models.PositiveIntegerField(default=0, verbose_name='Credits acquis')),
                ('ues_total', models.PositiveSmallIntegerField(default=0, verbose_name='UEs total')),
                ('ues_echec', models.PositiveSmallIntegerField(default=0, verbose_name='UEs en echec')),
                ('sessions_total', models.PositiveSmallIntegerField(default=0, verbose_name='Seances total')),
                ('sessions_presentes', models.PositiveSmallIntegerField(default=0, verbose_name='Seances presentes')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='accounts.profiletudiant', verbose_name='Etudiant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques', to='academics.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Historique academique',
                'verbose_name_plural': 'Historiques academiques',
                'db_table': 'historique_academique',
                'ordering': ['etudiant__matricule', '-semestre__annee'],
                'unique_together': {('etudiant', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='ResultatAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note /20')),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Credits obtenus')),
                ('valide', models.BooleanField(default=False, verbose_name='Valide')),
                ('session', models.CharField(choices=[('normale', 'Session normale'), ('rattrapage', 'Session de rattrapage')], default='normale', max_length=15, verbose_name='Session')),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'evaluation")),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.profiletudiant', verbose_name='Etudiant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='academics.semestre', verbose_name='Semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='academics.uniteenseignement', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Resultat academique',
                'verbose_name_plural': 'Resultats academiques',
                'db_table': 'resultat_academique',
                'ordering': ['etudiant__matricule', 'semestre__annee', 'ue__code'],
                'indexes': [models.Index(fields=['etudiant', 'semestre'], name='idx_res_etu_sem'), models.Index(fields=['ue', 'semestre'], name='idx_res_ue_sem')],
                'unique_together': {('etudiant', 'ue', 'semestre', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_cours', models.DateField(verbose_name='Date du cours')),
                ('present', models.BooleanField(default=True, verbose_name='Present')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='accounts.profiletudiant', verbose_name='Etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='academics.uniteenseignement', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'db_table': 'presence',
                'ordering': ['date_cours', 'etudiant__matricule'],
                'unique_together': {('etudiant', 'ue', 'date_cours')},
            },
        ),
    ]
