# Generated by Django 5.1.15 on 2026-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_profiladministrateur_profilenseignant_profiletudiant_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcoursacademique',
            index=models.Index(fields=['statut'], name='idx_parcours_statut'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['etudiant'], name='idx_presence_etu'),
        ),
    ]
