# Generated by Django 5.1.15 on 2026-07-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('source_id', models.PositiveIntegerField(unique=True, verbose_name='ID source (ProfilEtudiant)')),
                ('matricule', models.CharField(db_index=True, max_length=20, verbose_name='Matricule')),
                ('niveau_actuel', models.CharField(default='', max_length=5, verbose_name='Niveau actuel')),
                ('filiere', models.CharField(blank=True, default='', max_length=100, verbose_name='Filiere')),
                ('promotion', models.CharField(blank=True, default='', max_length=20, verbose_name='Promotion')),
                ('annee_scolaire', models.CharField(default='', max_length=9, verbose_name='Annee scolaire')),
            ],
            options={
                'verbose_name': 'Dim — Etudiant',
                'verbose_name_plural': 'Dim — Etudiants',
                'db_table': 'dim_etudiant',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='DimSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('source_id', models.PositiveIntegerField(unique=True, verbose_name='ID source (Semestre)')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numero')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Annee')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
            ],
            options={
                'verbose_name': 'Dim — Semestre',
                'verbose_name_plural': 'Dim — Semestres',
                'db_table': 'dim_semestre',
                'ordering': ['annee', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='DimTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Annee')),
                ('mois', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois')),
                ('session_examen', models.CharField(choices=[('normale', 'Normale'), ('rattrapage', 'Rattrapage')], default='normale', max_length=15, verbose_name='Session')),
                ('annee_scolaire', models.CharField(default='', max_length=9, verbose_name='Annee scolaire')),
            ],
            options={
                'verbose_name': 'Dim — Temps',
                'verbose_name_plural': 'Dim — Temps',
                'db_table': 'dim_temps',
                'ordering': ['annee', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='DimUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('source_id', models.PositiveIntegerField(unique=True, verbose_name='ID source (UniteEnseignement)')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Code UE')),
                ('intitule', models.CharField(blank=True, default='', max_length=200, verbose_name='Intitule')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Credits ECTS')),
                ('semestre', models.PositiveSmallIntegerField(default=1, verbose_name='Numero semestre')),
            ],
            options={
                'verbose_name': 'Dim — UE',
                'verbose_name_plural': 'Dim — UEs',
                'db_table': 'dim_ue',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FaitResultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note /20')),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Credits')),
                ('valide', models.BooleanField(default=False, verbose_name='Valide')),
                ('score_risque', models.FloatField(blank=True, null=True, verbose_name='Score de risque [0-100]')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faits', to='warehouse.dimetudiant', verbose_name='Etudiant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faits', to='warehouse.dimsemestre', verbose_name='Semestre')),
                ('temps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faits', to='warehouse.dimtemps', verbose_name='Temps')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faits', to='warehouse.dimue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Fait — Resultats',
                'verbose_name_plural': 'Fait — Resultats',
                'db_table': 'fait_resultats',
                'ordering': ['etudiant__matricule', 'semestre__annee', 'ue__code'],
                'indexes': [models.Index(fields=['etudiant', 'semestre'], name='idx_fait_etu_sem'), models.Index(fields=['ue', 'semestre'], name='idx_fait_ue_sem'), models.Index(fields=['score_risque'], name='idx_fait_score')],
            },
        ),
    ]
