# Generated by Django 5.1.15 on 2026-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('utilisateur', models.CharField(blank=True, default='', max_length=150, verbose_name='Utilisateur')),
                ('action', models.CharField(blank=True, default='', max_length=10, verbose_name='Action (HTTP)')),
                ('chemin', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('statut', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Statut HTTP')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', '-created_at'], name='idx_audit_user_time')],
            },
        ),
    ]
