# Generated by Django 5.1.15 on 2026-07-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_profiladministrateur_profilenseignant_profiletudiant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne generale /20')),
                ('score_risque', models.FloatField(blank=True, null=True, verbose_name='Score de risque [0-100]')),
                ('classification_risque', models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Modere', 'Modere'), ('Eleve', 'Eleve')], default='', max_length=10, verbose_name='Classification')),
                ('taux_progression', models.FloatField(blank=True, null=True, verbose_name='Taux de progression [%]')),
                ('credits_acquis', models.PositiveIntegerField(default=0, verbose_name='Credits acquis')),
                ('credits_total', models.PositiveIntegerField(default=0, verbose_name='Credits total vises')),
                ('ues_echec', models.PositiveSmallIntegerField(default=0, verbose_name='UEs en echec')),
                ('ues_total', models.PositiveSmallIntegerField(default=0, verbose_name='UEs total')),
                ('taux_absenteisme', models.FloatField(blank=True, null=True, verbose_name="Taux d'absenteisme [%]")),
                ('semestres_restants', models.FloatField(blank=True, null=True, verbose_name='Semestres restants estimes')),
                ('proj_diplomation', models.DateField(blank=True, null=True, verbose_name='Projection de diplomation')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='accounts.profiletudiant', verbose_name='Etudiant')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='academics.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Indicateur academique',
                'verbose_name_plural': 'Indicateurs academiques',
                'db_table': 'indicateur_academique',
                'ordering': ['etudiant__matricule', '-created_at'],
                'indexes': [models.Index(fields=['score_risque'], name='idx_indicateur_score')],
            },
        ),
    ]
