# Generated by Django 5.1.15 on 2026-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_index_phase15'),
        ('accounts', '0002_profiladministrateur_profilenseignant_profiletudiant_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicateuracademique',
            index=models.Index(fields=['etudiant', 'semestre'], name='idx_indic_etu_sem'),
        ),
        migrations.AddIndex(
            model_name='indicateuracademique',
            index=models.Index(fields=['classification_risque', 'semestre'], name='idx_indic_class_sem'),
        ),
    ]
